# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the workflow will run
on:

  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  initial:

    runs-on: ubuntu-latest
    steps: 
      - name: Run a one-line script
        run: echo Hello, world!


